# Generated by Django 6.0.3 on 2026-04-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('report_type', models.CharField(choices=[('SUMMARY', 'Summary'), ('PII_DETECTION', 'PII Detection'), ('DATA_EXTRACTION', 'Data Extraction'), ('SENTIMENT', 'Sentiment Analysis'), ('COMPLIANCE', 'Compliance Check')], default='SUMMARY', max_length=50)),
                ('parameters_json', models.JSONField(blank=True, default=dict, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChartArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('chart_type', models.CharField(choices=[('BAR_CHART', 'bar chart'), ('LINE_CHART', 'line chart'), ('PIE_CHART', 'pie chart'), ('SCATTER_CHART', 'scatter chart'), ('HISTOGRAM_CHART', 'histogram chart'), ('AREA_CHART', 'area chart'), ('BUBBLE_CHART', 'bubble chart'), ('CANDLESTICK_CHART', 'candlestick chart')], default='LINE_CHART', max_length=25)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='charts/%Y/%m/%d/')),
                ('config_json', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='analytics.analyticsreport')),
            ],
        ),
    ]
