# Generated by Django 6.0.3 on 2026-04-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(blank=True, null=True)),
                ('filters_json', models.JSONField(blank=True, default=dict, null=True)),
                ('results_count', models.IntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at', 'results_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('matched_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='documents.document')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='search_engine.searchquery')),
            ],
        ),
    ]
