# Generated by Django 6.0.3 on 2026-04-01 21:40

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('extension', models.CharField(blank=True, max_length=30, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_structured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('original_file_name', models.CharField(blank=True, max_length=150, null=True)),
                ('stored_file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(db_index=True, editable=False, max_length=64, null=True)),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'ordering': ['-uploaded_at', '-updated_at', 'file_size'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_status', models.CharField(choices=[('PENDING', 'pending'), ('STARTING', 'starting'), ('SUCCESS', 'success'), ('FAILED', 'failed'), ('UNSUPPORTED_FORMAT', 'unsupported format')], default='PENDING', max_length=50)),
                ('indexing_status', models.CharField(choices=[('WAITING', 'waiting'), ('INDEXING', 'indexing'), ('SUCCESS', 'success'), ('PARTIAL', 'partial'), ('FAILED', 'failed')], default='WAITING', max_length=50)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('detected_encoding', models.CharField(blank=True, max_length=30, null=True)),
                ('detected_language', models.CharField(blank=True, max_length=30, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='documents.document')),
            ],
            options={
                'ordering': ['-processed_at', 'row_count', 'column_count'],
            },
        ),
    ]
