"""Django settings for the InsightForge project."""

from pathlib import Path

# Base directory of the project; useful for building absolute file system paths.
BASE_DIR = Path(__file__).resolve().parent.parent

# Development-only secret key generated by Django.
# In production, this should come from environment variables or a secrets manager.
SECRET_KEY = 'django-insecure-h#j2f3#0!0_^4j&o+8qqof7$2wd99mh7j)cms=#&6=^-!fkrd^'

# Debug mode should stay enabled only in local development.
DEBUG = True

# Hosts allowed to serve this project in production.
ALLOWED_HOSTS = []

# Applications enabled for this Django project.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'documents.apps.DocumentsConfig',
    'search_engine.apps.SearchEngineConfig',
    'analytics.apps.AnalyticsConfig',
    'automation.apps.AutomationConfig',
    'api.apps.ApiConfig',
]

# Standard Django middleware stack.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Template settings for project-level and app-level templates.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application path used by traditional Python web servers.
WSGI_APPLICATION = 'config.wsgi.application'

# SQLite is used as the default development database.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Built-in password validators from Django.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization defaults.
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static file URL prefix.
STATIC_URL = 'static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'