# Generated by Django 6.0.3 on 2026-04-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'info'), ('WARNING', 'warning'), ('ERROR', 'error'), ('DEBUG', 'debug')], db_index=True, default='INFO', max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('context_json', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', 'source'],
            },
        ),
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('PROCESSING_TASK', 'processing'), ('ANALYTICS_TASK', 'analytics'), ('MAINTENANCE_TASK', 'maintenance'), ('INDEXING_TASK', 'indexing')], default='MAINTENANCE_TASK', max_length=30)),
                ('trigger_config_json', models.JSONField(blank=True, default=dict, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_jobs', to=settings.AUTH_USER_MODEL)),
                ('target_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationjob')),
            ],
            options={
                'ordering': ['-started_at', '-finished_at', 'job__name'],
            },
        ),
    ]
